### ISSUE TITLE
要来和幼女Code亲热吗？

### ISSUE THREAD

**Issue by RimoChan** [NitroRCr/Words-away#10]
把 https://github.com/RimoChan/unvcode 一起加进来，这样你就更厉害啦！

**Comment by NitroRCr** [comment]
这就去加上

**Comment by NitroRCr** [comment]
加上了。~~幼女真好用！~~

**Comment by RimoChan** [comment]
![](https://user-images.githubusercontent.com/20064807/125258048-8f79ed80-e330-11eb-9696-1f5235f6ed48.png)
