### ISSUE TITLE
期望兼容电话、QQ、邮箱、微信等号码

### ISSUE THREAD

**Issue by L-JH** [NitroRCr/Words-away#11]
期望兼容电话、QQ、邮箱、微信等号码，不然单独复制这些号码顺序会乱

**Comment by NitroRCr** [comment]
有空的话我会考虑实现的

**Comment by NitroRCr** [comment]
在实现过程中，有以下问题：
- 在双重反转模式下，如果保持号码字面顺序，那么它的显示顺序就是乱的。这点与链接不同，因为对于号码，手动输入的场景更多，并且乱序更难被发现
- 改功能与兼容链接功能冲突，因为链接中也存在长数字
因此，该功能目前不会实现

**Comment by L-JH** [comment]
谢谢，我的意思是反转的时候提供一个选项，不反转电话、QQ、邮箱、微信等号码，从各方面来说保持正常顺序。
