### ISSUE TITLE
将这个项目移植到了Cloudflare Workers

### ISSUE THREAD

**Issue by Ashes26** [NitroRCr/Words-away#8]
将这个项目移植到了Cloudflare Workers
https://words-away.typeboom.com/
![doge](https://img.typeboom.com/pic/2018new_doge02_org.png)

**Comment by NitroRCr** [comment]
把原链接换成新的域名吧：https://wordsaway.krytro.com/
那个域名要过期了

**Comment by Ashes26** [comment]
修改完成

**Comment by NitroRCr** [comment]
ok
