### ISSUE TITLE
酷安已不适用

### ISSUE THREAD

**Issue by People-11** [NitroRCr/Words-away#9]
酷安更新了检查策略，零宽间隔将会直接被忽略，反向字符将被识别为无法验证的字符而无法评论

**Comment by NitroRCr** [comment]
太久没管了。果然最终还是被酷安屏蔽了。我已经将U+200b替换为了U+2062，零宽间隔模式现在能用了，但反转还是没有办法

**Comment by People-11** [comment]
可以在两个字符间插入多个不同的零宽间隔符，我看那种类型的字符还蛮多的

**Comment by NitroRCr** [comment]
现在新的模式可以了

**Comment by People-11** [comment]
> 现在新的模式可以了

还是想要App（小声）（我是个不会编译的fw）

**Comment by NitroRCr** [comment]
那我弄成PWA吧，用起来一样的，这周末弄（大半年没碰，我已经不会Android开发了）

**Comment by NitroRCr** [comment]
> > 现在新的模式可以了
> 
> 还是想要App（小声）（我是个不会编译的fw）

现在支持PWA了
